# Generated by Django 6.0.1 on 2026-01-07 13:32

import django.db.models.deletion
import web.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, help_text='Valor del caudalímetro (m³/h)', max_digits=10)),
                ('ubicacion_manual', models.CharField(blank=True, help_text='Para uso interno de operarios', max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, help_text='Fotografía de evidencia', null=True, upload_to=web.models.medicion_photo_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de registro')),
                ('observation', models.TextField(blank=True, help_text='Observaciones adicionales (opcional)', null=True)),
                ('captured_latitude', models.FloatField(blank=True, help_text='Latitud capturada en el dispositivo', null=True)),
                ('captured_longitude', models.FloatField(blank=True, help_text='Longitud capturada en el dispositivo', null=True)),
                ('is_valid', models.BooleanField(default=False, help_text='¿La medición ha sido validada?')),
                ('user', models.ForeignKey(help_text='Usuario que cargó la medición', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medición',
                'verbose_name_plural': 'Mediciones',
                'ordering': ['-timestamp'],
            },
        ),
    ]
