# Generated by Django 6.0.1 on 2026-01-07 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación geográfica de la empresa / pozo', max_length=300, null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción general de la empresa', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(help_text='Usuario que representa a la empresa', on_delete=django.db.models.deletion.CASCADE, related_name='empresa_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Empresa',
                'verbose_name_plural': 'Perfiles de Empresa',
            },
        ),
    ]
