# Generated by Django 6.0.1 on 2026-01-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_empresaperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='target_latitude',
            field=models.FloatField(blank=True, help_text='Latitud objetivo / esperada', null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='target_longitude',
            field=models.FloatField(blank=True, help_text='Longitud objetivo / esperada', null=True),
        ),
    ]
