# Generated by Django 6.0.1 on 2026-02-01 01:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_medicion_target_latitude_medicion_target_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='captured_at',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora capturada desde EXIF del dispositivo', null=True),
        ),
        migrations.AddField(
            model_name='medicion',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha/hora en que el servidor recibió la medición'),
        ),
    ]
