# Generated by Django 6.0.1 on 2026-02-02 12:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_medicion_captured_at_medicion_uploaded_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medicion',
            index=models.Index(fields=['-timestamp'], name='web_medicio_timesta_7ca9bd_idx'),
        ),
        migrations.AddIndex(
            model_name='medicion',
            index=models.Index(fields=['user', '-timestamp'], name='web_medicio_user_id_f07afc_idx'),
        ),
        migrations.AddIndex(
            model_name='medicion',
            index=models.Index(fields=['captured_latitude', 'captured_longitude'], name='web_medicio_capture_f36797_idx'),
        ),
        migrations.AddIndex(
            model_name='medicion',
            index=models.Index(fields=['is_valid'], name='web_medicio_is_vali_949a15_idx'),
        ),
    ]
