# Generated by Django 6.0.1 on 2026-02-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_medicion_web_medicio_timesta_7ca9bd_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaperfil',
            name='icono',
            field=models.ImageField(blank=True, help_text='Ícono / logo de la empresa', null=True, upload_to='empresa_iconos/'),
        ),
    ]
