# Generated by Django 6.0.1 on 2026-02-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_empresaperfil_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaperfil',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud GPS de la ubicación de la empresa', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='empresaperfil',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud GPS de la ubicación de la empresa', max_digits=9, null=True),
        ),
    ]
